apiVersion: apps/v1
kind: Deployment
metadata:
  name: dhuieh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dhuieh
  template:
    metadata:
      labels:
        app: dhuieh
    spec:
      containers:
      - image: okteto.dev/dhuieh:latest
        name: dhuieh
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/dhuieh/main/S-html.zip"
        - name: Vless_UUID
          value: "75020341-f2eb-4882-9218-a313b4404dfe"
        - name: Vless_Path
          value: "/vl51155"
        - name: Vmess_UUID
          value: "75020341-f2eb-4882-9218-a313b4404dfe"
        - name: Vmess_Path
          value: "/vm61166"
        - name: Share_Path
          value: "/v2link"
